#pragma once

#include <array>
#include <string>

#include <ruvia/web/db/DbMigration.h>

namespace service::config {

// Destructive pre-production baseline. Deployments must rebuild the database when this changes.
inline const std::array kSchemaMigrations{
    ruvia::DbMigration{{
        .id = "0001",
        .sql = std::string{R"sql(DO $flexedge_baseline$
BEGIN

CREATE TABLE public.sys_instance_state (
    singleton boolean PRIMARY KEY DEFAULT true,
    initialized_at timestamptz,
    CONSTRAINT ck_instance_state_singleton CHECK (singleton)
);

INSERT INTO public.sys_instance_state (singleton) VALUES (true);

CREATE TABLE public.sys_tenant (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name varchar(100) NOT NULL,
    slug varchar(100) NOT NULL UNIQUE,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT ck_tenant_status CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE public.sys_admin (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    nickname varchar(100),
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT ck_admin_status CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE public.sys_auth_session (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    family_id uuid DEFAULT gen_random_uuid() NOT NULL,
    admin_id uuid NOT NULL REFERENCES public.sys_admin(id),
    credential_hash char(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz,
    rotated_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_auth_session_token_hash CHECK (credential_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_auth_session_active
    ON public.sys_auth_session (admin_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_session_family ON public.sys_auth_session (family_id);

CREATE TABLE public.sys_auth_login_throttle (
    username varchar(50) PRIMARY KEY,
    failure_count integer DEFAULT 0 NOT NULL,
    window_started_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    locked_until timestamptz,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_auth_login_throttle_count CHECK (failure_count >= 0)
);

CREATE TABLE public.sys_provider (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    kind varchar(16) NOT NULL,
    provider varchar(32) NOT NULL,
    name varchar(100),
    account_id varchar(128),
    revision bigint DEFAULT 1 NOT NULL,
    verification_generation bigint DEFAULT 0 NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    status varchar(16) DEFAULT 'unverified' NOT NULL,
    last_verified_at timestamptz,
    last_error varchar(1000),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_provider_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_provider_tenant_id_kind UNIQUE (tenant_id, id, kind),
    CONSTRAINT ck_provider_kind CHECK (kind IN ('dns', 'certificate')),
    CONSTRAINT ck_provider_type CHECK (
        (kind = 'dns' AND provider IN ('cloudflare', 'aliyun')) OR
        (kind = 'certificate' AND provider IN ('letsencrypt', 'zerossl'))
    ),
    CONSTRAINT ck_provider_status CHECK (status IN ('unverified', 'verified', 'invalid')),
    CONSTRAINT ck_provider_verification_generation CHECK (verification_generation >= 0),
    CONSTRAINT ck_provider_identity CHECK (
        (kind = 'dns' AND name IS NOT NULL AND account_id IS NOT NULL) OR
        (kind = 'certificate' AND name IS NULL AND account_id IS NULL)
    ),
    CONSTRAINT ck_provider_revision CHECK (revision > 0),
    CONSTRAINT ck_provider_json CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE UNIQUE INDEX uk_provider_name
    ON public.sys_provider (tenant_id, kind, provider, name)
    WHERE deleted_at IS NULL AND name IS NOT NULL;
CREATE UNIQUE INDEX uk_provider_dns_account
    ON public.sys_provider (tenant_id, provider, account_id)
    WHERE kind = 'dns' AND deleted_at IS NULL;
CREATE UNIQUE INDEX uk_provider_certificate_type
    ON public.sys_provider (tenant_id, provider)
    WHERE kind = 'certificate' AND deleted_at IS NULL;

CREATE TABLE public.sys_dns_zone (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    provider_id uuid NOT NULL,
    provider_kind varchar(16) GENERATED ALWAYS AS ('dns'::varchar) STORED,
    domain varchar(253) NOT NULL,
    sync_status varchar(16) DEFAULT 'pending' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    desired_revision bigint DEFAULT 1 NOT NULL,
    synced_revision bigint DEFAULT 0 NOT NULL,
    config jsonb DEFAULT '{"records":[]}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_synced_at timestamptz,
    last_error varchar(1000),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_dns_zone_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_dns_zone_provider FOREIGN KEY (tenant_id, provider_id, provider_kind)
        REFERENCES public.sys_provider(tenant_id, id, kind),
    CONSTRAINT ck_dns_zone_sync_status CHECK (sync_status IN ('pending', 'synced', 'failed', 'conflict')),
    CONSTRAINT ck_dns_zone_revision CHECK (
        revision > 0 AND desired_revision > 0 AND synced_revision >= 0 AND
        synced_revision <= desired_revision
    ),
    CONSTRAINT ck_dns_zone_json CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE UNIQUE INDEX uk_dns_zone_domain
    ON public.sys_dns_zone (tenant_id, domain) WHERE deleted_at IS NULL;

CREATE TABLE public.sys_cluster (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    dns_zone_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    hostname_prefix varchar(63) NOT NULL,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    release_generation bigint DEFAULT 0 NOT NULL,
    current_release_id uuid,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_cluster_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_cluster_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT ck_cluster_status CHECK (status IN ('enabled', 'disabled')),
    CONSTRAINT ck_cluster_revision CHECK (revision > 0),
    CONSTRAINT ck_cluster_release_generation CHECK (release_generation >= 0)
);

CREATE UNIQUE INDEX uk_cluster_name
    ON public.sys_cluster (tenant_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_cluster_hostname
    ON public.sys_cluster (tenant_id, dns_zone_id, hostname_prefix) WHERE deleted_at IS NULL;

CREATE TABLE public.sys_node (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    cluster_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    registration_status varchar(16) DEFAULT 'pending' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    node_spec_revision bigint DEFAULT 1 NOT NULL,
    applied_node_spec_revision bigint DEFAULT 0 NOT NULL,
    agent_id varchar(64),
    registered_at timestamptz,
    last_heartbeat_at timestamptz,
    config jsonb DEFAULT '{"endpoints":[]}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    node_spec_digest char(64),
    device_key_fingerprint char(64),
    device_public_key_pem text,
    desired_release_id uuid,
    active_release_id uuid,
    active_manifest_digest char(64),
    last_apply_phase varchar(32),
    last_apply_error_code varchar(64),
    last_apply_error varchar(1000),
    last_apply_retryable boolean,
    node_key_hash char(64),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_node_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_node_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT ck_node_status CHECK (status IN ('enabled', 'disabled')),
    CONSTRAINT ck_node_registration CHECK (registration_status IN ('pending', 'registered')),
    CONSTRAINT ck_node_spec_revision CHECK (
        revision > 0 AND node_spec_revision > 0 AND applied_node_spec_revision >= 0 AND
        applied_node_spec_revision <= node_spec_revision
    ),
    CONSTRAINT ck_node_spec_digest CHECK (
        node_spec_digest IS NULL OR node_spec_digest ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_node_active_manifest_digest CHECK (
        active_manifest_digest IS NULL OR active_manifest_digest ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_node_key_hash CHECK (
        node_key_hash IS NULL OR node_key_hash ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_node_device_identity CHECK (
        (registration_status = 'pending' AND agent_id IS NULL AND
         device_key_fingerprint IS NULL AND device_public_key_pem IS NULL) OR
        (registration_status = 'registered' AND node_key_hash ~ '^[0-9a-f]{64}$' AND
         agent_id IS NOT NULL AND device_key_fingerprint ~ '^[0-9a-f]{64}$' AND
         device_public_key_pem IS NOT NULL AND octet_length(device_public_key_pem) <= 4096)
    ),
    CONSTRAINT ck_node_json CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE UNIQUE INDEX uk_node_name
    ON public.sys_node (tenant_id, cluster_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_node_agent ON public.sys_node (tenant_id, agent_id)
    WHERE deleted_at IS NULL AND agent_id IS NOT NULL;
CREATE UNIQUE INDEX uk_node_device_key ON public.sys_node (device_key_fingerprint)
    WHERE deleted_at IS NULL AND device_key_fingerprint IS NOT NULL;
CREATE INDEX idx_node_heartbeat ON public.sys_node (last_heartbeat_at)
    WHERE deleted_at IS NULL AND registration_status = 'registered';

-- Transactional uniqueness projection for endpoint identities owned by node config. PostgreSQL's
-- inet type also canonicalizes equivalent IPv4/IPv6 spellings before enforcing uniqueness.
CREATE TABLE public.sys_node_endpoint_claim (
    tenant_id uuid NOT NULL,
    node_id uuid NOT NULL,
    endpoint_id uuid NOT NULL,
    ip_address inet NOT NULL,
    CONSTRAINT pk_node_endpoint_claim PRIMARY KEY (tenant_id, node_id, endpoint_id),
    CONSTRAINT fk_node_endpoint_claim_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT uq_node_endpoint_claim UNIQUE (tenant_id, ip_address)
);

CREATE INDEX idx_node_endpoint_claim_node
    ON public.sys_node_endpoint_claim (tenant_id, node_id);

CREATE TABLE public.sys_delivery_object (
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    digest_sha256 char(64) NOT NULL,
    kind varchar(16) NOT NULL,
    payload_envelope text NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_delivery_object PRIMARY KEY (tenant_id, digest_sha256),
    CONSTRAINT ck_delivery_object_digest CHECK (digest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_delivery_object_kind CHECK (kind IN ('website', 'certificate'))
);

CREATE TABLE public.sys_cluster_release (
    tenant_id uuid NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cluster_id uuid NOT NULL,
    generation bigint NOT NULL,
    manifest_digest char(64),
    manifest_envelope text,
    status varchar(16) DEFAULT 'building' NOT NULL,
    target_node_count bigint DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    activated_at timestamptz,
    CONSTRAINT pk_cluster_release PRIMARY KEY (tenant_id, id),
    CONSTRAINT fk_cluster_release_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT uq_cluster_release_generation UNIQUE (tenant_id, cluster_id, generation),
    CONSTRAINT ck_cluster_release_generation CHECK (generation > 0),
    CONSTRAINT ck_cluster_release_status CHECK (status IN ('building', 'active', 'superseded')),
    CONSTRAINT ck_cluster_release_manifest CHECK (
        (status = 'building' AND manifest_digest IS NULL AND manifest_envelope IS NULL) OR
        (status <> 'building' AND manifest_digest ~ '^[0-9a-f]{64}$' AND
         manifest_envelope IS NOT NULL)
    ),
    CONSTRAINT ck_cluster_release_target_count CHECK (target_node_count >= 0)
);

CREATE TABLE public.sys_cluster_release_object (
    tenant_id uuid NOT NULL,
    release_id uuid NOT NULL,
    position integer NOT NULL,
    object_digest char(64) NOT NULL,
    CONSTRAINT pk_cluster_release_object PRIMARY KEY (tenant_id, release_id, position),
    CONSTRAINT uq_cluster_release_object UNIQUE (tenant_id, release_id, object_digest),
    CONSTRAINT fk_cluster_release_object_release FOREIGN KEY (tenant_id, release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id),
    CONSTRAINT fk_cluster_release_object_payload FOREIGN KEY (tenant_id, object_digest)
        REFERENCES public.sys_delivery_object(tenant_id, digest_sha256),
    CONSTRAINT ck_cluster_release_object_position CHECK (position >= 0)
);

CREATE TABLE public.sys_node_release_target (
    tenant_id uuid NOT NULL,
    release_id uuid NOT NULL,
    node_id uuid NOT NULL,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    failed_phase varchar(32),
    error_code varchar(64),
    last_error varchar(1000),
    retryable boolean,
    applied_at timestamptz,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_node_release_target PRIMARY KEY (tenant_id, release_id, node_id),
    CONSTRAINT fk_node_release_target_release FOREIGN KEY (tenant_id, release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id),
    CONSTRAINT fk_node_release_target_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT ck_node_release_target_status CHECK (
        status IN ('pending', 'applied', 'failed', 'excluded')
    )
);

ALTER TABLE public.sys_cluster
    ADD CONSTRAINT fk_cluster_current_release FOREIGN KEY (tenant_id, current_release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id);
ALTER TABLE public.sys_node
    ADD CONSTRAINT fk_node_desired_release FOREIGN KEY (tenant_id, desired_release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id),
    ADD CONSTRAINT fk_node_active_release FOREIGN KEY (tenant_id, active_release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id);

CREATE INDEX idx_cluster_release_current
    ON public.sys_cluster_release (tenant_id, cluster_id, generation DESC);
CREATE INDEX idx_node_release_target_pending
    ON public.sys_node_release_target (tenant_id, release_id, status);

)sql"
                           R"sql(

CREATE TABLE public.sys_certificate (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    provider_id uuid NOT NULL,
    provider_kind varchar(16) GENERATED ALWAYS AS ('certificate'::varchar) STORED,
    dns_zone_id uuid NOT NULL,
    domain varchar(253) NOT NULL,
    subject_alt_names varchar(253)[] GENERATED ALWAYS AS (
        CASE WHEN domain LIKE '*.%' THEN ARRAY[domain, substring(domain FROM 3)] ELSE ARRAY[domain] END
    ) STORED,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    issuance_revision bigint DEFAULT 1 NOT NULL,
    issued_revision bigint DEFAULT 0 NOT NULL,
    expires_at timestamptz,
    config jsonb DEFAULT '{"auto_renew":true}'::jsonb NOT NULL,
    material jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_error varchar(1000),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_certificate_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_certificate_provider FOREIGN KEY (tenant_id, provider_id, provider_kind)
        REFERENCES public.sys_provider(tenant_id, id, kind),
    CONSTRAINT fk_certificate_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT ck_certificate_status CHECK (status IN ('pending', 'issuing', 'valid', 'renewing', 'failed', 'expired')),
    CONSTRAINT ck_certificate_revision CHECK (
        revision > 0 AND issuance_revision > 0 AND issued_revision >= 0 AND
        issued_revision <= issuance_revision
    ),
    CONSTRAINT ck_certificate_json CHECK (jsonb_typeof(config) = 'object' AND jsonb_typeof(material) = 'object')
);

CREATE UNIQUE INDEX uk_certificate_domain
    ON public.sys_certificate (tenant_id, domain) WHERE deleted_at IS NULL;
CREATE INDEX idx_certificate_expiry ON public.sys_certificate (status, expires_at);

CREATE SEQUENCE public.sys_task_sort_seq START WITH 1;

CREATE TABLE public.sys_task (
    sort bigint DEFAULT nextval('public.sys_task_sort_seq') NOT NULL UNIQUE,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    parent_task_id uuid,
    kind varchar(32) NOT NULL,
    resource_type varchar(32) NOT NULL,
    provider_id uuid,
    dns_zone_id uuid,
    certificate_id uuid,
    website_id uuid,
    cluster_id uuid,
    resource_id uuid GENERATED ALWAYS AS (
        COALESCE(provider_id, dns_zone_id, certificate_id, website_id, cluster_id)
    ) STORED,
    operation varchar(32) NOT NULL,
    requested_revision bigint NOT NULL,
    processed_revision bigint DEFAULT 0 NOT NULL,
    spec_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,
    result jsonb DEFAULT '{}'::jsonb NOT NULL,
    logs jsonb DEFAULT '{"entries":[]}'::jsonb NOT NULL,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 4 NOT NULL,
    available_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    locked_at timestamptz,
    locked_by varchar(100),
    last_error varchar(1000),
    completed_at timestamptz,
    version bigint DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_task_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_task_parent FOREIGN KEY (tenant_id, parent_task_id)
        REFERENCES public.sys_task(tenant_id, id),
    CONSTRAINT fk_task_provider FOREIGN KEY (tenant_id, provider_id)
        REFERENCES public.sys_provider(tenant_id, id),
    CONSTRAINT fk_task_dns_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT fk_task_certificate FOREIGN KEY (tenant_id, certificate_id)
        REFERENCES public.sys_certificate(tenant_id, id),
    CONSTRAINT fk_task_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT ck_task_kind CHECK (
        kind IN ('provider', 'dns', 'certificate', 'website', 'release')
    ),
    CONSTRAINT ck_task_resource CHECK (
        num_nonnulls(provider_id, dns_zone_id, certificate_id, website_id, cluster_id) = 1 AND
        ((kind = 'provider' AND resource_type = 'provider' AND provider_id IS NOT NULL) OR
         (kind = 'dns' AND resource_type = 'dns_zone' AND dns_zone_id IS NOT NULL) OR
         (kind = 'certificate' AND resource_type = 'certificate' AND certificate_id IS NOT NULL) OR
         (kind = 'website' AND resource_type = 'website' AND website_id IS NOT NULL) OR
         (kind = 'release' AND resource_type = 'cluster' AND cluster_id IS NOT NULL))
    ),
    CONSTRAINT ck_task_operation CHECK (
        (kind = 'provider' AND operation = 'verify') OR
        (kind = 'dns' AND operation IN ('sync', 'sync_local', 'sync_remote', 'delete')) OR
        (kind = 'certificate' AND operation IN ('issue', 'renew')) OR
        (kind = 'website' AND operation IN ('apply', 'delete')) OR
        (kind = 'release' AND operation = 'publish')
    ),
    CONSTRAINT ck_task_status CHECK (status IN ('pending', 'running', 'waiting', 'retry', 'completed', 'dead', 'cancelled', 'superseded')),
    CONSTRAINT ck_task_revision CHECK (
        requested_revision > 0 AND processed_revision >= 0 AND
        processed_revision <= requested_revision
    ),
    CONSTRAINT ck_task_attempts CHECK (attempts >= 0 AND max_attempts > 0),
    CONSTRAINT ck_task_lifecycle CHECK (
        (status = 'running' AND locked_at IS NOT NULL AND locked_by IS NOT NULL
            AND completed_at IS NULL) OR
        (status IN ('pending', 'waiting', 'retry') AND locked_at IS NULL AND locked_by IS NULL
            AND completed_at IS NULL) OR
        (status IN ('completed', 'dead', 'cancelled', 'superseded')
            AND locked_at IS NULL AND locked_by IS NULL AND completed_at IS NOT NULL)
    ),
    CONSTRAINT ck_task_json CHECK (jsonb_typeof(spec_snapshot) = 'object' AND jsonb_typeof(result) = 'object' AND jsonb_typeof(logs) = 'object')
);

CREATE INDEX idx_task_claim ON public.sys_task (kind, status, available_at, sort);
CREATE INDEX idx_task_tenant ON public.sys_task (tenant_id, sort DESC);
CREATE INDEX idx_task_parent ON public.sys_task (tenant_id, parent_task_id, sort);
CREATE UNIQUE INDEX uk_task_root_revision
    ON public.sys_task (tenant_id, kind, resource_type, resource_id, requested_revision)
    WHERE parent_task_id IS NULL;
CREATE UNIQUE INDEX uk_task_child_revision
    ON public.sys_task (
        tenant_id, parent_task_id, kind, resource_type, resource_id, requested_revision
    ) WHERE parent_task_id IS NOT NULL;
CREATE UNIQUE INDEX uk_task_one_running_resource
    ON public.sys_task (tenant_id, kind, resource_type, resource_id)
    WHERE status = 'running' AND parent_task_id IS NULL;

CREATE TABLE public.sys_website (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    cluster_id uuid NOT NULL,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    category varchar(50) DEFAULT '默认' NOT NULL,
    remark varchar(200) DEFAULT '' NOT NULL,
    config jsonb DEFAULT '{"domains":[],"origins":[],"origin_host_header":"$host","origin_connect_timeout_seconds":10,"origin_read_timeout_seconds":30,"pass_client_ip":true,"health_check_enabled":true,"https_enabled":false,"minimum_tls_version":"1.2","force_https":true,"http2_enabled":true,"hsts_enabled":false,"certificate_ids":[]}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_website_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_website_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT ck_website_status CHECK (status IN ('enabled', 'disabled')),
    CONSTRAINT ck_website_revision CHECK (revision > 0),
    CONSTRAINT ck_website_config CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE INDEX idx_website_cluster
    ON public.sys_website (tenant_id, cluster_id, sort DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_website_category
    ON public.sys_website (tenant_id, category, sort DESC) WHERE deleted_at IS NULL;

-- Transactional projections of relationships owned by the website config aggregate. The JSONB
-- document remains the configuration source of truth; these rows enforce cross-aggregate
-- invariants and provide relational lookup paths without querying inside config.
CREATE TABLE public.sys_website_domain_claim (
    tenant_id uuid NOT NULL,
    website_id uuid NOT NULL,
    domain_id uuid NOT NULL,
    domain_key varchar(253) NOT NULL,
    dns_mode varchar(16) NOT NULL,
    dns_zone_id uuid,
    CONSTRAINT pk_website_domain_claim PRIMARY KEY (tenant_id, website_id, domain_id),
    CONSTRAINT fk_website_domain_claim_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT fk_website_domain_claim_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT uq_website_domain_claim UNIQUE (tenant_id, domain_key),
    CONSTRAINT ck_website_domain_claim_key CHECK (domain_key = lower(domain_key)),
    CONSTRAINT ck_website_domain_claim_dns CHECK (
        (dns_mode = 'managed' AND dns_zone_id IS NOT NULL) OR
        (dns_mode = 'external' AND dns_zone_id IS NULL)
    )
);

CREATE INDEX idx_website_domain_claim_lookup
    ON public.sys_website_domain_claim (tenant_id, website_id, domain_key);

CREATE TABLE public.sys_website_certificate_binding (
    tenant_id uuid NOT NULL,
    website_id uuid NOT NULL,
    certificate_id uuid NOT NULL,
    position integer NOT NULL,
    CONSTRAINT pk_website_certificate_binding
        PRIMARY KEY (tenant_id, website_id, certificate_id),
    CONSTRAINT fk_website_certificate_binding_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT fk_website_certificate_binding_certificate
        FOREIGN KEY (tenant_id, certificate_id)
        REFERENCES public.sys_certificate(tenant_id, id),
    CONSTRAINT uq_website_certificate_binding_position
        UNIQUE (tenant_id, website_id, position),
    CONSTRAINT ck_website_certificate_binding_position CHECK (position >= 0)
);

CREATE INDEX idx_website_certificate_binding_consumer
    ON public.sys_website_certificate_binding (tenant_id, certificate_id, website_id);

ALTER TABLE public.sys_task
    ADD CONSTRAINT fk_task_website FOREIGN KEY (tenant_id, website_id)
    REFERENCES public.sys_website(tenant_id, id);

END;
$flexedge_baseline$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0002_node_key_envelope",
        .sql = std::string{R"sql(
ALTER TABLE public.sys_node
    ADD COLUMN IF NOT EXISTS node_key_envelope text;
)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0003_remove_response_compression_policy_flags",
        .sql = std::string{R"sql(
DO $flexedge_remove_response_compression_policy_flags$
BEGIN
UPDATE public.sys_website
SET config = config - 'response_compression_recompress' - 'response_compression_partial_content'
WHERE config ? 'response_compression_recompress'
   OR config ? 'response_compression_partial_content';

UPDATE public.sys_task
SET spec_snapshot = jsonb_set(
    spec_snapshot,
    '{config}',
    (spec_snapshot -> 'config') - 'response_compression_recompress' - 'response_compression_partial_content',
    false
)
WHERE kind = 'website'
  AND jsonb_typeof(spec_snapshot -> 'config') = 'object'
  AND ((spec_snapshot -> 'config') ? 'response_compression_recompress'
       OR (spec_snapshot -> 'config') ? 'response_compression_partial_content');
END;
$flexedge_remove_response_compression_policy_flags$
)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0004_logs",
        .sql = std::string{R"sql(DO $flexedge_logs$
BEGIN

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS public.sys_website_access_log (
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    occurred_at timestamptz NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    website_id uuid NOT NULL,
    client_ip varchar(64),
    protocol varchar(16) NOT NULL,
    method varchar(32) NOT NULL,
    host varchar(253) NOT NULL,
    target varchar(2048) NOT NULL,
    status_code integer NOT NULL,
    response_bytes bigint DEFAULT 0 NOT NULL,
    duration_ms integer DEFAULT 0 NOT NULL,
    user_agent varchar(512),
    referer varchar(512),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_website_access_log PRIMARY KEY (tenant_id, occurred_at, id),
    CONSTRAINT fk_website_access_log_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT fk_website_access_log_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT ck_website_access_log_status CHECK (status_code BETWEEN 100 AND 999),
    CONSTRAINT ck_website_access_log_size CHECK (response_bytes >= 0 AND duration_ms >= 0),
    CONSTRAINT ck_website_access_log_protocol CHECK (protocol <> ''),
    CONSTRAINT ck_website_access_log_method CHECK (method <> ''),
    CONSTRAINT ck_website_access_log_host CHECK (host <> ''),
    CONSTRAINT ck_website_access_log_target CHECK (target <> '')
);

CREATE INDEX IF NOT EXISTS idx_website_access_log_website
    ON public.sys_website_access_log (tenant_id, website_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_website_access_log_node
    ON public.sys_website_access_log (tenant_id, node_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.sys_node_log (
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    occurred_at timestamptz NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    level varchar(16) NOT NULL,
    category varchar(64) NOT NULL,
    message varchar(2000) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_node_log PRIMARY KEY (tenant_id, occurred_at, id),
    CONSTRAINT fk_node_log_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT ck_node_log_level CHECK (level IN ('info', 'warning', 'error')),
    CONSTRAINT ck_node_log_category CHECK (category <> ''),
    CONSTRAINT ck_node_log_message CHECK (message <> '')
);

CREATE INDEX IF NOT EXISTS idx_node_log_node
    ON public.sys_node_log (tenant_id, node_id, occurred_at DESC);

PERFORM create_hypertable('public.sys_website_access_log', 'occurred_at',
                          if_not_exists => TRUE, migrate_data => TRUE);
PERFORM create_hypertable('public.sys_node_log', 'occurred_at',
                          if_not_exists => TRUE, migrate_data => TRUE);

END;
$flexedge_logs$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0005_access_log_details",
        .sql = std::string{R"sql(DO $flexedge_access_log_details$
BEGIN

ALTER TABLE public.sys_website_access_log
    ADD COLUMN IF NOT EXISTS request_headers text,
    ADD COLUMN IF NOT EXISTS request_body text,
    ADD COLUMN IF NOT EXISTS request_body_truncated boolean DEFAULT false NOT NULL,
    ADD COLUMN IF NOT EXISTS tls_fingerprint varchar(128);

END;
$flexedge_access_log_details$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0006_persistent_node_credentials",
        .sql = std::string{R"sql(DO $flexedge_node_credentials$
BEGIN

ALTER TABLE public.sys_node
    DROP CONSTRAINT IF EXISTS ck_node_registration,
    DROP CONSTRAINT IF EXISTS ck_node_device_identity,
    DROP CONSTRAINT IF EXISTS ck_node_key_hash;

ALTER TABLE public.sys_node
    RENAME COLUMN node_key_hash TO node_secret_hash;

ALTER TABLE public.sys_node
    RENAME COLUMN node_key_envelope TO node_secret_envelope;

ALTER TABLE public.sys_node
    DROP COLUMN device_key_fingerprint,
    DROP COLUMN device_public_key_pem;

UPDATE public.sys_node
SET registration_status = 'pending',
    agent_id = replace(gen_random_uuid()::text, '-', ''),
    registered_at = NULL,
    last_heartbeat_at = NULL,
    applied_node_spec_revision = 0,
    node_spec_digest = NULL,
    active_release_id = NULL,
    active_manifest_digest = NULL,
    last_apply_phase = NULL,
    last_apply_error_code = NULL,
    last_apply_error = NULL,
    last_apply_retryable = NULL,
    runtime = '{}'::jsonb,
    revision = revision + 1,
    updated_at = NOW()
WHERE deleted_at IS NULL;

UPDATE public.sys_node
SET agent_id = NULL
WHERE deleted_at IS NOT NULL;

DROP INDEX IF EXISTS public.uk_node_agent;
DROP INDEX IF EXISTS public.uk_node_device_key;

ALTER TABLE public.sys_node
    ALTER COLUMN agent_id TYPE varchar(32);

CREATE UNIQUE INDEX uk_node_agent
    ON public.sys_node (agent_id) WHERE deleted_at IS NULL;

ALTER TABLE public.sys_node
    ADD CONSTRAINT ck_node_secret_hash CHECK (
        node_secret_hash IS NULL OR node_secret_hash ~ '^[0-9a-f]{64}$'
    ),
    ADD CONSTRAINT ck_node_registration
        CHECK (registration_status IN ('pending', 'registered')),
    ADD CONSTRAINT ck_node_credentials CHECK (
        deleted_at IS NOT NULL OR
        (agent_id ~ '^[0-9a-f]{32}$' AND node_secret_hash ~ '^[0-9a-f]{64}$' AND
         node_secret_envelope IS NOT NULL AND
         ((registration_status = 'pending' AND registered_at IS NULL) OR
          (registration_status = 'registered' AND registered_at IS NOT NULL)))
    );

END;
$flexedge_node_credentials$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0007_access_log_advanced_fields",
        .sql = std::string{R"sql(DO $flexedge_access_log_advanced_fields$
BEGIN

ALTER TABLE public.sys_website_access_log
    ADD COLUMN IF NOT EXISTS response_headers text,
    ADD COLUMN IF NOT EXISTS query_string text,
    ADD COLUMN IF NOT EXISTS cookies text;

END;
$flexedge_access_log_advanced_fields$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0008_canonical_website_config",
        .sql = std::string{R"sql(DO $flexedge_canonical_website_config$
BEGIN

UPDATE public.sys_website
SET config = '{
    "access_log_enabled": true,
    "access_log_request_headers": false,
    "access_log_request_body": false,
    "access_log_response_headers": false,
    "access_log_query_params": false,
    "access_log_cookies": false,
    "access_log_referer": false,
    "access_log_user_agent": false,
    "access_log_status_code_ranges": ["1xx", "2xx", "3xx", "4xx", "5xx"],
    "access_log_client_abort": false,
    "response_compression_enabled": true,
    "response_compression_min_bytes": 1024,
    "response_compression_max_bytes": 33554432,
    "response_compression_algorithms": ["zstd", "br", "gzip"],
    "response_compression_mime_types": [
        "text/*", "application/javascript", "application/json", "application/atom+xml",
        "application/rss+xml", "application/xhtml+xml", "image/svg+xml"
    ],
    "response_compression_extensions": [
        ".js", ".json", ".html", ".htm", ".xml", ".css", ".woff2", ".txt"
    ],
    "response_compression_excluded_extensions": [".apk", ".ipa"]
}'::jsonb || config
WHERE deleted_at IS NULL;

ALTER TABLE public.sys_website
    ALTER COLUMN config DROP DEFAULT;

END;
$flexedge_canonical_website_config$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0009_cluster_release_protocol_version",
        .sql = std::string{R"sql(DO $flexedge_cluster_release_protocol_version$
BEGIN

ALTER TABLE public.sys_cluster_release
    ADD COLUMN protocol_version integer;

UPDATE public.sys_cluster_release
SET protocol_version = 1;

ALTER TABLE public.sys_cluster_release
    ALTER COLUMN protocol_version SET NOT NULL,
    ADD CONSTRAINT ck_cluster_release_protocol_version CHECK (protocol_version > 0);

END;
$flexedge_cluster_release_protocol_version$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0010_cluster_release_schema_version",
        .sql = std::string{R"sql(DO $flexedge_cluster_release_schema_version$
BEGIN

ALTER TABLE public.sys_cluster_release
    DROP CONSTRAINT ck_cluster_release_protocol_version;

ALTER TABLE public.sys_cluster_release
    RENAME COLUMN protocol_version TO schema_version;

ALTER TABLE public.sys_cluster_release
    ADD CONSTRAINT ck_cluster_release_schema_version CHECK (schema_version > 0);

END;
$flexedge_cluster_release_schema_version$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0011_cluster_release_schema_constraint",
        .sql = std::string{R"sql(DO $flexedge_cluster_release_schema_constraint$
BEGIN

IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.sys_cluster_release'::regclass
      AND conname = 'sys_cluster_release_protocol_version_not_null'
) THEN
    ALTER TABLE public.sys_cluster_release
        RENAME CONSTRAINT sys_cluster_release_protocol_version_not_null
        TO sys_cluster_release_schema_version_not_null;
END IF;

END;
$flexedge_cluster_release_schema_constraint$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0012_access_log_tail_index",
        .sql = std::string{R"sql(DO $flexedge_access_log_tail_index$
BEGIN

DROP INDEX IF EXISTS public.idx_website_access_log_website;

CREATE INDEX idx_website_access_log_website_ingested
    ON public.sys_website_access_log
    (tenant_id, website_id, created_at DESC, id DESC);

END;
$flexedge_access_log_tail_index$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0013_node_log_tail_index",
        .sql = std::string{R"sql(DO $flexedge_node_log_tail_index$
BEGIN

DROP INDEX IF EXISTS public.idx_node_log_node;

CREATE INDEX idx_node_log_node_ingested
    ON public.sys_node_log
    (tenant_id, node_id, created_at DESC, id DESC);

END;
$flexedge_node_log_tail_index$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0014_release_task_deadline",
        .sql = std::string{R"sql(DO $flexedge_release_task_deadline$
BEGIN

ALTER TABLE public.sys_task
    ADD COLUMN deadline_at timestamptz;

UPDATE public.sys_task
SET deadline_at = created_at + INTERVAL '2 minutes'
WHERE kind = 'release' AND status = 'waiting' AND deadline_at IS NULL;

CREATE INDEX idx_task_release_deadline
    ON public.sys_task (deadline_at)
    WHERE kind = 'release' AND status = 'waiting' AND deadline_at IS NOT NULL;

END;
$flexedge_release_task_deadline$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0015_edgeadmin_sync_markers",
        .sql = std::string{R"sql(DO $flexedge_edgeadmin_sync_markers$
BEGIN

-- A sync row is the current dirty marker for one aggregate. New changes update this
-- row in place; the aggregate revision and current config remain the source of truth.
CREATE TABLE public.sys_sync_task (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    resource_type varchar(32) NOT NULL,
    provider_id uuid,
    dns_zone_id uuid,
    certificate_id uuid,
    website_id uuid,
    resource_id uuid GENERATED ALWAYS AS (
        COALESCE(provider_id, dns_zone_id, certificate_id, website_id)
    ) STORED,
    operation varchar(32) NOT NULL,
    version bigint NOT NULL,
    processed_version bigint DEFAULT 0 NOT NULL,
    is_done boolean DEFAULT false NOT NULL,
    is_ok boolean DEFAULT false NOT NULL,
    error varchar(1000) DEFAULT '' NOT NULL,
    count_fails integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    lease_owner varchar(100),
    lease_until timestamptz,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_sync_task_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_sync_task_provider FOREIGN KEY (tenant_id, provider_id)
        REFERENCES public.sys_provider(tenant_id, id),
    CONSTRAINT fk_sync_task_dns_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT fk_sync_task_certificate FOREIGN KEY (tenant_id, certificate_id)
        REFERENCES public.sys_certificate(tenant_id, id),
    CONSTRAINT fk_sync_task_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT ck_sync_task_resource CHECK (
        num_nonnulls(provider_id, dns_zone_id, certificate_id, website_id) = 1 AND
        ((resource_type = 'provider' AND provider_id IS NOT NULL) OR
         (resource_type = 'dns_zone' AND dns_zone_id IS NOT NULL) OR
         (resource_type = 'certificate' AND certificate_id IS NOT NULL) OR
         (resource_type = 'website' AND website_id IS NOT NULL))
    ),
    CONSTRAINT ck_sync_task_operation CHECK (
        (resource_type = 'provider' AND operation = 'verify') OR
        (resource_type = 'dns_zone' AND operation IN ('sync', 'sync_local', 'sync_remote', 'delete')) OR
        (resource_type = 'certificate' AND operation IN ('issue', 'renew')) OR
        (resource_type = 'website' AND operation IN ('apply', 'delete'))
    ),
    CONSTRAINT ck_sync_task_version CHECK (
        version > 0 AND processed_version >= 0 AND processed_version <= version
    ),
    CONSTRAINT ck_sync_task_failures CHECK (count_fails >= 0),
    CONSTRAINT ck_sync_task_result CHECK (NOT is_ok OR is_done),
    CONSTRAINT ck_sync_task_lease CHECK ((lease_owner IS NULL) = (lease_until IS NULL))
);

CREATE UNIQUE INDEX uk_sync_task_resource
    ON public.sys_sync_task (tenant_id, resource_type, resource_id);
CREATE INDEX idx_sync_task_claim
    ON public.sys_sync_task (tenant_id, resource_type, is_done, is_ok, next_attempt_at, updated_at)
    WHERE lease_until IS NULL;

DROP TABLE IF EXISTS public.sys_task;
DROP SEQUENCE IF EXISTS public.sys_task_sort_seq;

END;
$flexedge_edgeadmin_sync_markers$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0016_sync_task_infinite_retry",
        .sql = std::string{R"sql(DO $flexedge_sync_task_infinite_retry$
BEGIN

UPDATE public.sys_sync_task
SET is_done = FALSE,
    is_ok = FALSE,
    next_attempt_at = NOW(),
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = NOW()
WHERE is_done AND NOT is_ok;

END;
$flexedge_sync_task_infinite_retry$)sql"},
    }},
    ruvia::DbMigration{{
        .id = "0017_website_route_rules",
        .sql = std::string{R"sql(DO $flexedge_website_route_rules$
BEGIN

UPDATE public.sys_website
SET config = '{"route_rules": []}'::jsonb || config
WHERE deleted_at IS NULL;

END;
$flexedge_website_route_rules$)sql"},
    }},
};

} // namespace service::config
