#pragma once

#include <array>
#include <string>

#include <ruvia/web/db/DbMigration.h>

namespace service::config {

// Destructive pre-production baseline. Deployments must rebuild the database when this changes.
inline const std::array kSchemaMigrations{
    ruvia::DbMigration{{
        .id = "0001",
        .sql = std::string{R"sql(DO $flexedge_baseline$
BEGIN

CREATE TABLE public.sys_instance_state (
    singleton boolean PRIMARY KEY DEFAULT true,
    initialized_at timestamptz,
    CONSTRAINT ck_instance_state_singleton CHECK (singleton)
);

INSERT INTO public.sys_instance_state (singleton) VALUES (true);

CREATE TABLE public.sys_tenant (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name varchar(100) NOT NULL,
    slug varchar(100) NOT NULL UNIQUE,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT ck_tenant_status CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE public.sys_admin (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    nickname varchar(100),
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT ck_admin_status CHECK (status IN ('enabled', 'disabled'))
);

CREATE TABLE public.sys_auth_session (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    family_id uuid DEFAULT gen_random_uuid() NOT NULL,
    admin_id uuid NOT NULL REFERENCES public.sys_admin(id),
    credential_hash char(64) NOT NULL,
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz,
    rotated_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_auth_session_token_hash CHECK (credential_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_auth_session_active
    ON public.sys_auth_session (admin_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_session_family ON public.sys_auth_session (family_id);

CREATE TABLE public.sys_auth_login_throttle (
    username varchar(50) PRIMARY KEY,
    failure_count integer DEFAULT 0 NOT NULL,
    window_started_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    locked_until timestamptz,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_auth_login_throttle_count CHECK (failure_count >= 0)
);

CREATE TABLE public.sys_provider (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    kind varchar(16) NOT NULL,
    provider varchar(32) NOT NULL,
    name varchar(100),
    account_id varchar(128),
    revision bigint DEFAULT 1 NOT NULL,
    verification_generation bigint DEFAULT 0 NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    status varchar(16) DEFAULT 'unverified' NOT NULL,
    last_verified_at timestamptz,
    last_error varchar(1000),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_provider_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_provider_tenant_id_kind UNIQUE (tenant_id, id, kind),
    CONSTRAINT ck_provider_kind CHECK (kind IN ('dns', 'certificate')),
    CONSTRAINT ck_provider_type CHECK (
        (kind = 'dns' AND provider IN ('cloudflare', 'aliyun')) OR
        (kind = 'certificate' AND provider IN ('letsencrypt', 'zerossl'))
    ),
    CONSTRAINT ck_provider_status CHECK (status IN ('unverified', 'verified', 'invalid')),
    CONSTRAINT ck_provider_verification_generation CHECK (verification_generation >= 0),
    CONSTRAINT ck_provider_identity CHECK (
        (kind = 'dns' AND name IS NOT NULL AND account_id IS NOT NULL) OR
        (kind = 'certificate' AND name IS NULL AND account_id IS NULL)
    ),
    CONSTRAINT ck_provider_revision CHECK (revision > 0),
    CONSTRAINT ck_provider_json CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE UNIQUE INDEX uk_provider_name
    ON public.sys_provider (tenant_id, kind, provider, name)
    WHERE deleted_at IS NULL AND name IS NOT NULL;
CREATE UNIQUE INDEX uk_provider_dns_account
    ON public.sys_provider (tenant_id, provider, account_id)
    WHERE kind = 'dns' AND deleted_at IS NULL;
CREATE UNIQUE INDEX uk_provider_certificate_type
    ON public.sys_provider (tenant_id, provider)
    WHERE kind = 'certificate' AND deleted_at IS NULL;

CREATE TABLE public.sys_dns_zone (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    provider_id uuid NOT NULL,
    provider_kind varchar(16) GENERATED ALWAYS AS ('dns'::varchar) STORED,
    domain varchar(253) NOT NULL,
    sync_status varchar(16) DEFAULT 'pending' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    desired_revision bigint DEFAULT 1 NOT NULL,
    synced_revision bigint DEFAULT 0 NOT NULL,
    config jsonb DEFAULT '{"records":[]}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_synced_at timestamptz,
    last_error varchar(1000),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_dns_zone_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_dns_zone_provider FOREIGN KEY (tenant_id, provider_id, provider_kind)
        REFERENCES public.sys_provider(tenant_id, id, kind),
    CONSTRAINT ck_dns_zone_sync_status CHECK (sync_status IN ('pending', 'synced', 'failed', 'conflict')),
    CONSTRAINT ck_dns_zone_revision CHECK (
        revision > 0 AND desired_revision > 0 AND synced_revision >= 0 AND
        synced_revision <= desired_revision
    ),
    CONSTRAINT ck_dns_zone_json CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE UNIQUE INDEX uk_dns_zone_domain
    ON public.sys_dns_zone (tenant_id, domain) WHERE deleted_at IS NULL;

CREATE TABLE public.sys_cluster (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    dns_zone_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    hostname_prefix varchar(63) NOT NULL,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    release_generation bigint DEFAULT 0 NOT NULL,
    current_release_id uuid,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_cluster_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_cluster_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT ck_cluster_status CHECK (status IN ('enabled', 'disabled')),
    CONSTRAINT ck_cluster_revision CHECK (revision > 0),
    CONSTRAINT ck_cluster_release_generation CHECK (release_generation >= 0)
);

CREATE UNIQUE INDEX uk_cluster_name
    ON public.sys_cluster (tenant_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_cluster_hostname
    ON public.sys_cluster (tenant_id, dns_zone_id, hostname_prefix) WHERE deleted_at IS NULL;

CREATE TABLE public.sys_node (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    cluster_id uuid NOT NULL,
    name varchar(100) NOT NULL,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    registration_status varchar(16) DEFAULT 'pending' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    node_spec_revision bigint DEFAULT 1 NOT NULL,
    applied_node_spec_revision bigint DEFAULT 0 NOT NULL,
    agent_id varchar(32),
    registered_at timestamptz,
    last_heartbeat_at timestamptz,
    config jsonb DEFAULT '{"endpoints":[]}'::jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    node_spec_digest char(64),
    desired_release_id uuid,
    active_release_id uuid,
    active_manifest_digest char(64),
    last_apply_phase varchar(32),
    last_apply_error_code varchar(64),
    last_apply_error varchar(1000),
    last_apply_retryable boolean,
    node_secret_hash char(64),
    node_secret_envelope text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_node_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_node_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT ck_node_status CHECK (status IN ('enabled', 'disabled')),
    CONSTRAINT ck_node_registration CHECK (registration_status IN ('pending', 'registered')),
    CONSTRAINT ck_node_spec_revision CHECK (
        revision > 0 AND node_spec_revision > 0 AND applied_node_spec_revision >= 0 AND
        applied_node_spec_revision <= node_spec_revision
    ),
    CONSTRAINT ck_node_spec_digest CHECK (
        node_spec_digest IS NULL OR node_spec_digest ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_node_active_manifest_digest CHECK (
        active_manifest_digest IS NULL OR active_manifest_digest ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_node_secret_hash CHECK (
        node_secret_hash IS NULL OR node_secret_hash ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_node_credentials CHECK (
        deleted_at IS NOT NULL OR
        (agent_id ~ '^[0-9a-f]{32}$' AND node_secret_hash ~ '^[0-9a-f]{64}$' AND
         node_secret_envelope IS NOT NULL AND
         ((registration_status = 'pending' AND registered_at IS NULL) OR
          (registration_status = 'registered' AND registered_at IS NOT NULL)))
    ),
    CONSTRAINT ck_node_json CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE UNIQUE INDEX uk_node_name
    ON public.sys_node (tenant_id, cluster_id, name) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_node_agent
    ON public.sys_node (agent_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_node_heartbeat ON public.sys_node (last_heartbeat_at)
    WHERE deleted_at IS NULL AND registration_status = 'registered';

-- Transactional uniqueness projection for endpoint identities owned by node config. PostgreSQL's
-- inet type also canonicalizes equivalent IPv4/IPv6 spellings before enforcing uniqueness.
CREATE TABLE public.sys_node_endpoint_claim (
    tenant_id uuid NOT NULL,
    node_id uuid NOT NULL,
    endpoint_id uuid NOT NULL,
    ip_address inet NOT NULL,
    CONSTRAINT pk_node_endpoint_claim PRIMARY KEY (tenant_id, node_id, endpoint_id),
    CONSTRAINT fk_node_endpoint_claim_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT uq_node_endpoint_claim UNIQUE (tenant_id, ip_address)
);

CREATE INDEX idx_node_endpoint_claim_node
    ON public.sys_node_endpoint_claim (tenant_id, node_id);

CREATE TABLE public.sys_delivery_object (
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    digest_sha256 char(64) NOT NULL,
    kind varchar(16) NOT NULL,
    payload_envelope text NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_delivery_object PRIMARY KEY (tenant_id, digest_sha256),
    CONSTRAINT ck_delivery_object_digest CHECK (digest_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_delivery_object_kind CHECK (kind IN ('website', 'certificate'))
);

CREATE TABLE public.sys_cluster_release (
    tenant_id uuid NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    cluster_id uuid NOT NULL,
    generation bigint NOT NULL,
    schema_version integer NOT NULL,
    manifest_digest char(64),
    manifest_envelope text,
    status varchar(16) DEFAULT 'building' NOT NULL,
    target_node_count bigint DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    activated_at timestamptz,
    CONSTRAINT pk_cluster_release PRIMARY KEY (tenant_id, id),
    CONSTRAINT fk_cluster_release_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT uq_cluster_release_generation UNIQUE (tenant_id, cluster_id, generation),
    CONSTRAINT ck_cluster_release_generation CHECK (generation > 0),
    CONSTRAINT ck_cluster_release_schema_version CHECK (schema_version > 0),
    CONSTRAINT ck_cluster_release_status CHECK (status IN ('building', 'active', 'superseded')),
    CONSTRAINT ck_cluster_release_manifest CHECK (
        (status = 'building' AND manifest_digest IS NULL AND manifest_envelope IS NULL) OR
        (status <> 'building' AND manifest_digest ~ '^[0-9a-f]{64}$' AND
         manifest_envelope IS NOT NULL)
    ),
    CONSTRAINT ck_cluster_release_target_count CHECK (target_node_count >= 0)
);

CREATE TABLE public.sys_cluster_release_object (
    tenant_id uuid NOT NULL,
    release_id uuid NOT NULL,
    position integer NOT NULL,
    object_digest char(64) NOT NULL,
    CONSTRAINT pk_cluster_release_object PRIMARY KEY (tenant_id, release_id, position),
    CONSTRAINT uq_cluster_release_object UNIQUE (tenant_id, release_id, object_digest),
    CONSTRAINT fk_cluster_release_object_release FOREIGN KEY (tenant_id, release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id),
    CONSTRAINT fk_cluster_release_object_payload FOREIGN KEY (tenant_id, object_digest)
        REFERENCES public.sys_delivery_object(tenant_id, digest_sha256),
    CONSTRAINT ck_cluster_release_object_position CHECK (position >= 0)
);

CREATE TABLE public.sys_node_release_target (
    tenant_id uuid NOT NULL,
    release_id uuid NOT NULL,
    node_id uuid NOT NULL,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    failed_phase varchar(32),
    error_code varchar(64),
    last_error varchar(1000),
    retryable boolean,
    applied_at timestamptz,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_node_release_target PRIMARY KEY (tenant_id, release_id, node_id),
    CONSTRAINT fk_node_release_target_release FOREIGN KEY (tenant_id, release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id),
    CONSTRAINT fk_node_release_target_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT ck_node_release_target_status CHECK (
        status IN ('pending', 'applied', 'failed', 'excluded')
    )
);

ALTER TABLE public.sys_cluster
    ADD CONSTRAINT fk_cluster_current_release FOREIGN KEY (tenant_id, current_release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id);
ALTER TABLE public.sys_node
    ADD CONSTRAINT fk_node_desired_release FOREIGN KEY (tenant_id, desired_release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id),
    ADD CONSTRAINT fk_node_active_release FOREIGN KEY (tenant_id, active_release_id)
        REFERENCES public.sys_cluster_release(tenant_id, id);

CREATE INDEX idx_cluster_release_current
    ON public.sys_cluster_release (tenant_id, cluster_id, generation DESC);
CREATE INDEX idx_node_release_target_pending
    ON public.sys_node_release_target (tenant_id, release_id, status);

)sql"
                           R"sql(

CREATE TABLE public.sys_certificate (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    provider_id uuid NOT NULL,
    provider_kind varchar(16) GENERATED ALWAYS AS ('certificate'::varchar) STORED,
    dns_zone_id uuid NOT NULL,
    domain varchar(253) NOT NULL,
    subject_alt_names varchar(253)[] GENERATED ALWAYS AS (
        CASE WHEN domain LIKE '*.%' THEN ARRAY[domain, substring(domain FROM 3)] ELSE ARRAY[domain] END
    ) STORED,
    status varchar(16) DEFAULT 'pending' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    issuance_revision bigint DEFAULT 1 NOT NULL,
    issued_revision bigint DEFAULT 0 NOT NULL,
    expires_at timestamptz,
    config jsonb DEFAULT '{"auto_renew":true}'::jsonb NOT NULL,
    material jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_error varchar(1000),
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_certificate_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_certificate_provider FOREIGN KEY (tenant_id, provider_id, provider_kind)
        REFERENCES public.sys_provider(tenant_id, id, kind),
    CONSTRAINT fk_certificate_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT ck_certificate_status CHECK (status IN ('pending', 'issuing', 'valid', 'renewing', 'failed', 'expired')),
    CONSTRAINT ck_certificate_revision CHECK (
        revision > 0 AND issuance_revision > 0 AND issued_revision >= 0 AND
        issued_revision <= issuance_revision
    ),
    CONSTRAINT ck_certificate_json CHECK (jsonb_typeof(config) = 'object' AND jsonb_typeof(material) = 'object')
);

CREATE UNIQUE INDEX uk_certificate_domain
    ON public.sys_certificate (tenant_id, domain) WHERE deleted_at IS NULL;
CREATE INDEX idx_certificate_expiry ON public.sys_certificate (status, expires_at);

CREATE TABLE public.sys_website (
    sort bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    cluster_id uuid NOT NULL,
    status varchar(16) DEFAULT 'enabled' NOT NULL,
    revision bigint DEFAULT 1 NOT NULL,
    category varchar(50) DEFAULT '默认' NOT NULL,
    remark varchar(200) DEFAULT '' NOT NULL,
    config jsonb NOT NULL,
    runtime jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamptz,
    CONSTRAINT uq_website_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_website_cluster FOREIGN KEY (tenant_id, cluster_id)
        REFERENCES public.sys_cluster(tenant_id, id),
    CONSTRAINT ck_website_status CHECK (status IN ('enabled', 'disabled')),
    CONSTRAINT ck_website_revision CHECK (revision > 0),
    CONSTRAINT ck_website_config CHECK (
        jsonb_typeof(config) = 'object' AND jsonb_typeof(runtime) = 'object'
    )
);

CREATE INDEX idx_website_cluster
    ON public.sys_website (tenant_id, cluster_id, sort DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_website_category
    ON public.sys_website (tenant_id, category, sort DESC) WHERE deleted_at IS NULL;

-- Transactional projections of relationships owned by the website config aggregate. The JSONB
-- document remains the configuration source of truth; these rows enforce cross-aggregate
-- invariants and provide relational lookup paths without querying inside config.
CREATE TABLE public.sys_website_domain_claim (
    tenant_id uuid NOT NULL,
    website_id uuid NOT NULL,
    domain_id uuid NOT NULL,
    domain_key varchar(253) NOT NULL,
    dns_mode varchar(16) NOT NULL,
    dns_zone_id uuid,
    CONSTRAINT pk_website_domain_claim PRIMARY KEY (tenant_id, website_id, domain_id),
    CONSTRAINT fk_website_domain_claim_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT fk_website_domain_claim_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT uq_website_domain_claim UNIQUE (tenant_id, domain_key),
    CONSTRAINT ck_website_domain_claim_key CHECK (domain_key = lower(domain_key)),
    CONSTRAINT ck_website_domain_claim_dns CHECK (
        (dns_mode = 'managed' AND dns_zone_id IS NOT NULL) OR
        (dns_mode = 'external' AND dns_zone_id IS NULL)
    )
);

CREATE INDEX idx_website_domain_claim_lookup
    ON public.sys_website_domain_claim (tenant_id, website_id, domain_key);

CREATE TABLE public.sys_website_certificate_binding (
    tenant_id uuid NOT NULL,
    website_id uuid NOT NULL,
    certificate_id uuid NOT NULL,
    position integer NOT NULL,
    CONSTRAINT pk_website_certificate_binding
        PRIMARY KEY (tenant_id, website_id, certificate_id),
    CONSTRAINT fk_website_certificate_binding_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT fk_website_certificate_binding_certificate
        FOREIGN KEY (tenant_id, certificate_id)
        REFERENCES public.sys_certificate(tenant_id, id),
    CONSTRAINT uq_website_certificate_binding_position
        UNIQUE (tenant_id, website_id, position),
    CONSTRAINT ck_website_certificate_binding_position CHECK (position >= 0)
);

CREATE INDEX idx_website_certificate_binding_consumer
    ON public.sys_website_certificate_binding (tenant_id, certificate_id, website_id);

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE public.sys_website_access_log (
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    occurred_at timestamptz NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    website_id uuid NOT NULL,
    client_ip varchar(64),
    protocol varchar(16) NOT NULL,
    method varchar(32) NOT NULL,
    host varchar(253) NOT NULL,
    target varchar(2048) NOT NULL,
    status_code integer NOT NULL,
    request_bytes bigint DEFAULT 0 NOT NULL,
    response_bytes bigint DEFAULT 0 NOT NULL,
    duration_ms integer DEFAULT 0 NOT NULL,
    user_agent varchar(512),
    referer varchar(512),
    request_headers text,
    request_body text,
    request_body_truncated boolean DEFAULT false NOT NULL,
    tls_fingerprint varchar(128),
    response_headers text,
    query_string text,
    cookies text,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_website_access_log PRIMARY KEY (tenant_id, occurred_at, id),
    CONSTRAINT fk_website_access_log_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT fk_website_access_log_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT ck_website_access_log_status CHECK (status_code BETWEEN 100 AND 999),
    CONSTRAINT ck_website_access_log_size CHECK (response_bytes >= 0 AND duration_ms >= 0),
    CONSTRAINT ck_website_access_log_protocol CHECK (protocol <> ''),
    CONSTRAINT ck_website_access_log_method CHECK (method <> ''),
    CONSTRAINT ck_website_access_log_host CHECK (host <> ''),
    CONSTRAINT ck_website_access_log_target CHECK (target <> '')
);

CREATE INDEX idx_website_access_log_website_ingested
    ON public.sys_website_access_log (tenant_id, website_id, created_at DESC, id DESC);
CREATE INDEX idx_website_access_log_node
    ON public.sys_website_access_log (tenant_id, node_id, occurred_at DESC);
CREATE INDEX idx_website_access_log_website_occurred
    ON public.sys_website_access_log (tenant_id, website_id, occurred_at DESC);

CREATE TABLE public.sys_node_log (
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    occurred_at timestamptz NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    node_id uuid NOT NULL,
    level varchar(16) NOT NULL,
    category varchar(64) NOT NULL,
    message varchar(2000) NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_node_log PRIMARY KEY (tenant_id, occurred_at, id),
    CONSTRAINT fk_node_log_node FOREIGN KEY (tenant_id, node_id)
        REFERENCES public.sys_node(tenant_id, id),
    CONSTRAINT ck_node_log_level CHECK (level IN ('info', 'warning', 'error')),
    CONSTRAINT ck_node_log_category CHECK (category <> ''),
    CONSTRAINT ck_node_log_message CHECK (message <> '')
);

CREATE INDEX idx_node_log_node_ingested
    ON public.sys_node_log (tenant_id, node_id, created_at DESC, id DESC);

PERFORM create_hypertable('public.sys_website_access_log', 'occurred_at');
PERFORM create_hypertable('public.sys_node_log', 'occurred_at');

-- One row is the current dirty marker for an aggregate. The aggregate revision and
-- its current configuration remain the source of truth; completed work is not kept.
CREATE TABLE public.sys_sync_task (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    resource_type varchar(32) NOT NULL,
    provider_id uuid,
    dns_zone_id uuid,
    certificate_id uuid,
    website_id uuid,
    resource_id uuid GENERATED ALWAYS AS (
        COALESCE(provider_id, dns_zone_id, certificate_id, website_id)
    ) STORED,
    operation varchar(32) NOT NULL,
    version bigint NOT NULL,
    processed_version bigint DEFAULT 0 NOT NULL,
    is_done boolean DEFAULT false NOT NULL,
    is_ok boolean DEFAULT false NOT NULL,
    error varchar(1000) DEFAULT '' NOT NULL,
    count_fails integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    lease_owner varchar(100),
    lease_until timestamptz,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_sync_task_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_sync_task_provider FOREIGN KEY (tenant_id, provider_id)
        REFERENCES public.sys_provider(tenant_id, id),
    CONSTRAINT fk_sync_task_dns_zone FOREIGN KEY (tenant_id, dns_zone_id)
        REFERENCES public.sys_dns_zone(tenant_id, id),
    CONSTRAINT fk_sync_task_certificate FOREIGN KEY (tenant_id, certificate_id)
        REFERENCES public.sys_certificate(tenant_id, id),
    CONSTRAINT fk_sync_task_website FOREIGN KEY (tenant_id, website_id)
        REFERENCES public.sys_website(tenant_id, id),
    CONSTRAINT ck_sync_task_resource CHECK (
        num_nonnulls(provider_id, dns_zone_id, certificate_id, website_id) = 1 AND
        ((resource_type = 'provider' AND provider_id IS NOT NULL) OR
         (resource_type = 'dns_zone' AND dns_zone_id IS NOT NULL) OR
         (resource_type = 'certificate' AND certificate_id IS NOT NULL) OR
         (resource_type = 'website' AND website_id IS NOT NULL))
    ),
    CONSTRAINT ck_sync_task_operation CHECK (
        (resource_type = 'provider' AND operation = 'verify') OR
        (resource_type = 'dns_zone' AND operation IN ('sync', 'sync_local', 'sync_remote', 'delete')) OR
        (resource_type = 'certificate' AND operation IN ('issue', 'renew')) OR
        (resource_type = 'website' AND operation = 'apply')
    ),
    CONSTRAINT ck_sync_task_version CHECK (
        version > 0 AND processed_version >= 0 AND processed_version <= version
    ),
    CONSTRAINT ck_sync_task_failures CHECK (count_fails >= 0),
    CONSTRAINT ck_sync_task_result CHECK (NOT is_ok OR is_done),
    CONSTRAINT ck_sync_task_lease CHECK ((lease_owner IS NULL) = (lease_until IS NULL))
);

CREATE UNIQUE INDEX uk_sync_task_resource
    ON public.sys_sync_task (tenant_id, resource_type, resource_id);
CREATE INDEX idx_sync_task_claim
    ON public.sys_sync_task (tenant_id, resource_type, is_done, is_ok, next_attempt_at, updated_at)
    WHERE lease_until IS NULL;

-- Immutable result events let connected clients consume every worker result without
-- inferring transitions from a bounded snapshot of the current-state markers.
CREATE TABLE public.sys_sync_event (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL REFERENCES public.sys_tenant(id),
    task_id uuid NOT NULL,
    resource_type varchar(32) NOT NULL,
    resource_id uuid NOT NULL,
    operation varchar(32) NOT NULL,
    version bigint NOT NULL,
    outcome varchar(16) NOT NULL,
    emitted_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ck_sync_event_resource_type CHECK (
        resource_type IN ('provider', 'dns_zone', 'certificate', 'website')
    ),
    CONSTRAINT ck_sync_event_version CHECK (version > 0),
    CONSTRAINT ck_sync_event_outcome CHECK (outcome IN ('completed', 'failed'))
);

CREATE INDEX idx_sync_event_tenant_id
    ON public.sys_sync_event (tenant_id, id);
CREATE INDEX idx_sync_event_emitted_at
    ON public.sys_sync_event (emitted_at);

END;
$flexedge_baseline$)sql"},
    }},
};

} // namespace service::config
