#pragma once

#include <ruvia/web/Model.h>

namespace service::website_config {

RUVIA_REQUEST_MODEL(WebsiteDomainInput, RUVIA_OPTIONAL_FIELD(id, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(hostname, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("dns_mode", dnsMode, ruvia::String));
RUVIA_REQUEST_MODEL(WebsiteOriginInput, RUVIA_OPTIONAL_FIELD(id, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("group", group, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(protocol, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(host, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(port, ruvia::Int64),
                    RUVIA_OPTIONAL_FIELD(role, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(weight, ruvia::Int64),
                    RUVIA_OPTIONAL_FIELD(status, ruvia::String));
RUVIA_REQUEST_MODEL(WebsiteRouteHeaderInput, RUVIA_OPTIONAL_FIELD(name, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(value, ruvia::String));
RUVIA_REQUEST_MODEL(WebsiteRouteRuleInput, RUVIA_OPTIONAL_FIELD(id, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(name, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(description, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(hostnames, ruvia::Array<ruvia::String>),
                    RUVIA_OPTIONAL_FIELD_NAME("rewrite_mode", rewriteMode, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("query_mode", queryMode, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("query_string", queryString, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(status, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("match_type", matchType, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(path, ruvia::String),
                    RUVIA_OPTIONAL_FIELD(methods, ruvia::Array<ruvia::String>),
                    RUVIA_OPTIONAL_FIELD(action, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("rewrite_path", rewritePath, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("redirect_url", redirectUrl, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("redirect_status", redirectStatus, ruvia::Int64),
                    RUVIA_OPTIONAL_FIELD_NAME("origin_group", originGroup, ruvia::String),
                    RUVIA_OPTIONAL_FIELD_NAME("request_headers", requestHeaders,
                                              ruvia::Array<WebsiteRouteHeaderInput>),
                    RUVIA_OPTIONAL_FIELD_NAME("response_headers", responseHeaders,
                                              ruvia::Array<WebsiteRouteHeaderInput>));
RUVIA_REQUEST_MODEL(
    WebsiteConfigInput, RUVIA_OPTIONAL_FIELD(name, ruvia::String),
    RUVIA_OPTIONAL_FIELD(domains, ruvia::Array<WebsiteDomainInput>),
    RUVIA_OPTIONAL_FIELD(origins, ruvia::Array<WebsiteOriginInput>),
    RUVIA_OPTIONAL_FIELD_NAME("default_origin_group", defaultOriginGroup, ruvia::String),
    RUVIA_OPTIONAL_FIELD_NAME("origin_host_header", originHostHeader, ruvia::String),
    RUVIA_OPTIONAL_FIELD_NAME("origin_connect_timeout_seconds", originConnectTimeoutSeconds,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("origin_read_timeout_seconds", originReadTimeoutSeconds,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("pass_client_ip", passClientIp, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("health_check_enabled", healthCheckEnabled, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("health_check_path", healthCheckPath, ruvia::String),
    RUVIA_OPTIONAL_FIELD_NAME("health_check_interval_seconds", healthCheckIntervalSeconds,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("health_check_timeout_seconds", healthCheckTimeoutSeconds,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("health_check_expected_status", healthCheckExpectedStatus,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("healthy_threshold", healthyThreshold, ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("unhealthy_threshold", unhealthyThreshold, ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_enabled", accessLogEnabled, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_request_headers", accessLogRequestHeaders, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_request_body", accessLogRequestBody, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_response_headers", accessLogResponseHeaders, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_query_params", accessLogQueryParams, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_cookies", accessLogCookies, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_referer", accessLogReferer, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_user_agent", accessLogUserAgent, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_status_code_ranges", accessLogStatusCodeRanges,
                              ruvia::Array<ruvia::String>),
    RUVIA_OPTIONAL_FIELD_NAME("access_log_client_abort", accessLogClientAbort, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("https_enabled", httpsEnabled, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("certificate_ids", certificateIds, ruvia::Array<ruvia::String>),
    RUVIA_OPTIONAL_FIELD_NAME("minimum_tls_version", minimumTlsVersion, ruvia::String),
    RUVIA_OPTIONAL_FIELD_NAME("force_https", forceHttps, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("http2_enabled", http2Enabled, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("hsts_enabled", hstsEnabled, ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_enabled", responseCompressionEnabled,
                              ruvia::Bool),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_min_bytes", responseCompressionMinBytes,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_max_bytes", responseCompressionMaxBytes,
                              ruvia::Int64),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_algorithms", responseCompressionAlgorithms,
                              ruvia::Array<ruvia::String>),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_mime_types", responseCompressionMimeTypes,
                              ruvia::Array<ruvia::String>),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_extensions", responseCompressionExtensions,
                              ruvia::Array<ruvia::String>),
    RUVIA_OPTIONAL_FIELD_NAME("response_compression_excluded_extensions",
                              responseCompressionExcludedExtensions, ruvia::Array<ruvia::String>),
    RUVIA_OPTIONAL_FIELD_NAME("route_rules", routeRules, ruvia::Array<WebsiteRouteRuleInput>));

RUVIA_RESPONSE_MODEL(WebsiteDomainOutput, RUVIA_REQUIRED_FIELD(id, ruvia::String),
                     RUVIA_REQUIRED_FIELD(hostname, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("dns_mode", dnsMode, ruvia::String));
RUVIA_RESPONSE_MODEL(WebsiteOriginOutput, RUVIA_REQUIRED_FIELD(id, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("group", group, ruvia::String),
                     RUVIA_REQUIRED_FIELD(protocol, ruvia::String),
                     RUVIA_REQUIRED_FIELD(host, ruvia::String),
                     RUVIA_REQUIRED_FIELD(port, ruvia::Int64),
                     RUVIA_REQUIRED_FIELD(role, ruvia::String),
                     RUVIA_REQUIRED_FIELD(weight, ruvia::Int64),
                     RUVIA_REQUIRED_FIELD(status, ruvia::String));
RUVIA_RESPONSE_MODEL(WebsiteRouteHeaderOutput, RUVIA_REQUIRED_FIELD(name, ruvia::String),
                     RUVIA_REQUIRED_FIELD(value, ruvia::String));
RUVIA_RESPONSE_MODEL(WebsiteRouteRuleOutput, RUVIA_REQUIRED_FIELD(id, ruvia::String),
                     RUVIA_REQUIRED_FIELD(name, ruvia::String),
                     RUVIA_REQUIRED_FIELD(description, ruvia::String),
                     RUVIA_REQUIRED_FIELD(hostnames, ruvia::Array<ruvia::String>),
                     RUVIA_REQUIRED_FIELD_NAME("rewrite_mode", rewriteMode, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("query_mode", queryMode, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("query_string", queryString, ruvia::String),
                     RUVIA_REQUIRED_FIELD(status, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("match_type", matchType, ruvia::String),
                     RUVIA_REQUIRED_FIELD(path, ruvia::String),
                     RUVIA_REQUIRED_FIELD(methods, ruvia::Array<ruvia::String>),
                     RUVIA_REQUIRED_FIELD(action, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("rewrite_path", rewritePath, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("redirect_url", redirectUrl, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("redirect_status", redirectStatus, ruvia::Int64),
                     RUVIA_REQUIRED_FIELD_NAME("origin_group", originGroup, ruvia::String),
                     RUVIA_REQUIRED_FIELD_NAME("request_headers", requestHeaders,
                                               ruvia::Array<WebsiteRouteHeaderOutput>),
                     RUVIA_REQUIRED_FIELD_NAME("response_headers", responseHeaders,
                                               ruvia::Array<WebsiteRouteHeaderOutput>));
RUVIA_RESPONSE_MODEL(
    WebsiteConfigOutput, RUVIA_OPTIONAL_FIELD(name, ruvia::String),
    RUVIA_REQUIRED_FIELD(domains, ruvia::Array<WebsiteDomainOutput>),
    RUVIA_REQUIRED_FIELD(origins, ruvia::Array<WebsiteOriginOutput>),
    RUVIA_REQUIRED_FIELD_NAME("default_origin_group", defaultOriginGroup, ruvia::String),
    RUVIA_REQUIRED_FIELD_NAME("origin_host_header", originHostHeader, ruvia::String),
    RUVIA_REQUIRED_FIELD_NAME("origin_connect_timeout_seconds", originConnectTimeoutSeconds,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("origin_read_timeout_seconds", originReadTimeoutSeconds,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("pass_client_ip", passClientIp, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("health_check_enabled", healthCheckEnabled, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("health_check_path", healthCheckPath, ruvia::String),
    RUVIA_REQUIRED_FIELD_NAME("health_check_interval_seconds", healthCheckIntervalSeconds,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("health_check_timeout_seconds", healthCheckTimeoutSeconds,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("health_check_expected_status", healthCheckExpectedStatus,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("healthy_threshold", healthyThreshold, ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("unhealthy_threshold", unhealthyThreshold, ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("access_log_enabled", accessLogEnabled, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_request_headers", accessLogRequestHeaders, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_request_body", accessLogRequestBody, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_response_headers", accessLogResponseHeaders, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_query_params", accessLogQueryParams, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_cookies", accessLogCookies, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_referer", accessLogReferer, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_user_agent", accessLogUserAgent, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("access_log_status_code_ranges", accessLogStatusCodeRanges,
                              ruvia::Array<ruvia::String>),
    RUVIA_REQUIRED_FIELD_NAME("access_log_client_abort", accessLogClientAbort, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("https_enabled", httpsEnabled, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("certificate_ids", certificateIds, ruvia::Array<ruvia::String>),
    RUVIA_REQUIRED_FIELD_NAME("minimum_tls_version", minimumTlsVersion, ruvia::String),
    RUVIA_REQUIRED_FIELD_NAME("force_https", forceHttps, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("http2_enabled", http2Enabled, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("hsts_enabled", hstsEnabled, ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_enabled", responseCompressionEnabled,
                              ruvia::Bool),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_min_bytes", responseCompressionMinBytes,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_max_bytes", responseCompressionMaxBytes,
                              ruvia::Int64),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_algorithms", responseCompressionAlgorithms,
                              ruvia::Array<ruvia::String>),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_mime_types", responseCompressionMimeTypes,
                              ruvia::Array<ruvia::String>),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_extensions", responseCompressionExtensions,
                              ruvia::Array<ruvia::String>),
    RUVIA_REQUIRED_FIELD_NAME("response_compression_excluded_extensions",
                              responseCompressionExcludedExtensions, ruvia::Array<ruvia::String>),
    RUVIA_REQUIRED_FIELD_NAME("route_rules", routeRules, ruvia::Array<WebsiteRouteRuleOutput>));

} // namespace service::website_config
