/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedClustersRouteImport } from './routes/_authenticated/clusters'
import { Route as AuthenticatedDnsZonesRouteImport } from './routes/_authenticated/dns-zones'
import { Route as AuthenticatedNodesRouteImport } from './routes/_authenticated/nodes'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedWebsitesRouteImport } from './routes/_authenticated/websites'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClustersRoute = AuthenticatedClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnsZonesRoute = AuthenticatedDnsZonesRouteImport.update({
  id: '/dns-zones',
  path: '/dns-zones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNodesRoute = AuthenticatedNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsitesRoute = AuthenticatedWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/sign-in': typeof SignInRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/clusters': typeof AuthenticatedClustersRoute
  '/dns-zones': typeof AuthenticatedDnsZonesRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/websites': typeof AuthenticatedWebsitesRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/clusters': typeof AuthenticatedClustersRoute
  '/dns-zones': typeof AuthenticatedDnsZonesRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/websites': typeof AuthenticatedWebsitesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/clusters': typeof AuthenticatedClustersRoute
  '/_authenticated/dns-zones': typeof AuthenticatedDnsZonesRoute
  '/_authenticated/nodes': typeof AuthenticatedNodesRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/websites': typeof AuthenticatedWebsitesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/certificates'
    | '/clusters'
    | '/dns-zones'
    | '/nodes'
    | '/providers'
    | '/tasks'
    | '/websites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/certificates'
    | '/clusters'
    | '/dns-zones'
    | '/nodes'
    | '/providers'
    | '/tasks'
    | '/websites'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/sign-in'
    | '/_authenticated/certificates'
    | '/_authenticated/clusters'
    | '/_authenticated/dns-zones'
    | '/_authenticated/nodes'
    | '/_authenticated/providers'
    | '/_authenticated/tasks'
    | '/_authenticated/websites'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clusters': {
      id: '/_authenticated/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AuthenticatedClustersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dns-zones': {
      id: '/_authenticated/dns-zones'
      path: '/dns-zones'
      fullPath: '/dns-zones'
      preLoaderRoute: typeof AuthenticatedDnsZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nodes': {
      id: '/_authenticated/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthenticatedNodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/websites': {
      id: '/_authenticated/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof AuthenticatedWebsitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedClustersRoute: typeof AuthenticatedClustersRoute
  AuthenticatedDnsZonesRoute: typeof AuthenticatedDnsZonesRoute
  AuthenticatedNodesRoute: typeof AuthenticatedNodesRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWebsitesRoute: typeof AuthenticatedWebsitesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedClustersRoute: AuthenticatedClustersRoute,
  AuthenticatedDnsZonesRoute: AuthenticatedDnsZonesRoute,
  AuthenticatedNodesRoute: AuthenticatedNodesRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWebsitesRoute: AuthenticatedWebsitesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
